// Package codegen converts translator results into HCL (.tf) output.
package codegen

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"

	"github.com/terra-translate/internal/ir"
	"github.com/terra-translate/internal/translator"
)

// Generator converts a translation result into HCL output files.
type Generator struct {
	targetProvider string
}

// New creates a Generator for the given target provider name.
func New(targetProvider string) *Generator {
	return &Generator{targetProvider: targetProvider}
}

// WriteHCL writes the translated resources to path as a valid Terraform file.
func (g *Generator) WriteHCL(path string, result *translator.Result) error {
	f := hclwrite.NewEmptyFile()
	root := f.Body()

	g.writeHeader(root)
	g.writeModuleInterface(root, result)

	for _, tr := range result.TargetResources {
		if tr == nil {
			continue
		}
		g.writeResource(root, tr)
	}

	if len(result.Warnings) > 0 {
		g.writeWarnings(root, result.Warnings)
	}

	// hclwrite.Format also assigns canonical spacing to raw expression tokens.
	// This keeps generated modules ready for `terraform fmt -check`.
	return os.WriteFile(path, hclwrite.Format(f.Bytes()), 0644)
}

// writeModuleInterface preserves the public variable/output contract relied on
// by callers such as Terragrunt. Resource references in outputs are rewritten
// through the same graph as resource attributes.
func (g *Generator) writeModuleInterface(root *hclwrite.Body, result *translator.Result) {
	if result.SourceModule == nil {
		return
	}

	for _, name := range sortedKeys(result.SourceModule.Variables) {
		variable := result.SourceModule.Variables[name]
		block := root.AppendNewBlock("variable", []string{name})
		body := block.Body()
		if variable.Type != "" {
			typeExpr := strings.TrimSuffix(strings.TrimPrefix(variable.Type, "${"), "}")
			body.SetAttributeRaw("type", hclwrite.Tokens{{Bytes: []byte(typeExpr)}})
		}
		if variable.Description != "" {
			body.SetAttributeValue("description", cty.StringVal(variable.Description))
		}
		if variable.Default != nil {
			writeAttr(body, "default", variable.Default)
		}
		if variable.Sensitive {
			body.SetAttributeValue("sensitive", cty.True)
		}
		root.AppendNewline()
	}

	if len(result.SourceModule.Locals) > 0 {
		block := root.AppendNewBlock("locals", nil)
		for _, name := range sortedKeys(result.SourceModule.Locals) {
			writeAttr(block.Body(), name, rewriteInterfaceRef(result.SourceModule.Locals[name], result.RefGraph))
		}
		root.AppendNewline()
	}

	for _, name := range sortedKeys(result.SourceModule.Outputs) {
		output := result.SourceModule.Outputs[name]
		block := root.AppendNewBlock("output", []string{name})
		body := block.Body()
		if output.Value != nil {
			writeAttr(body, "value", rewriteInterfaceRef(output.Value, result.RefGraph))
		}
		if output.Description != "" {
			body.SetAttributeValue("description", cty.StringVal(output.Description))
		}
		if output.Sensitive {
			body.SetAttributeValue("sensitive", cty.True)
		}
		root.AppendNewline()
	}
}

func rewriteInterfaceRef(value interface{}, graph *ir.RefGraph) interface{} {
	ref, ok := value.(string)
	if !ok || !strings.HasPrefix(ref, "${") || !strings.HasSuffix(ref, "}") {
		return value
	}
	return "${" + graph.Rewrite(ref[2:len(ref)-1]) + "}"
}

func (g *Generator) writeHeader(root *hclwrite.Body) {
	src := providerSource(g.targetProvider)
	header := fmt.Sprintf(
		`# Generated by terra-translate — target provider: %s
# Review ALL resources before applying. Attributes marked TODO require manual replacement.

terraform {
  required_providers {
    %s = {
      source = %q
    }
  }
}

`, g.targetProvider, g.targetProvider, src)

	root.AppendUnstructuredTokens(hclwrite.Tokens{
		{Bytes: []byte(header)},
	})
}

func (g *Generator) writeResource(root *hclwrite.Body, tr *ir.TargetResource) {
	if strings.HasPrefix(tr.ProviderType, "#") {
		root.AppendUnstructuredTokens(hclwrite.Tokens{
			{Bytes: []byte(fmt.Sprintf(
				"\n# ╔═ UNMAPPED RESOURCE ═══════════════════════════════════════\n"+
					"# ║ %s.%s\n"+
					"# ║ %s\n"+
					"# ║ Attributes: %s\n"+
					"# ╚════════════════════════════════════════════════════════════\n",
				tr.OriginalResource.OriginalType, tr.Name,
				tr.Comment,
				strings.Join(tr.UnmappedAttrs, ", "),
			))},
		})
		return
	}

	comment := fmt.Sprintf("\n# Translated from: %s.%s",
		tr.OriginalResource.OriginalType, tr.Name)
	if tr.Comment != "" {
		comment += "\n# " + tr.Comment
	}
	if len(tr.UnmappedAttrs) > 0 {
		comment += fmt.Sprintf("\n# Unmapped attrs (manual review): %s",
			strings.Join(tr.UnmappedAttrs, ", "))
	}
	comment += "\n"
	root.AppendUnstructuredTokens(hclwrite.Tokens{
		{Bytes: []byte(comment)},
	})

	block := root.AppendNewBlock("resource", []string{tr.ProviderType, tr.Name})
	body := block.Body()

	// Flat attributes.
	for _, k := range sortedKeys(tr.Attributes) {
		v := tr.Attributes[k]
		if todo, ok := tr.TodoAttrs[k]; ok {
			body.AppendUnstructuredTokens(hclwrite.Tokens{
				{Bytes: []byte(fmt.Sprintf("  # TODO: %s\n", todo))},
			})
		}
		writeAttr(body, k, v)
	}

	// Recursive nested blocks.
	tree := buildBlockTree(tr.NestedBlocks, tr.TodoAttrs)
	writeBlockTree(body, tree, tr.TodoAttrs, "")

	// Lifecycle.
	meta := tr.OriginalResource.Meta
	if meta.PreventDestroy || meta.CreateBeforeDestroy {
		body.AppendNewline()
		lc := body.AppendNewBlock("lifecycle", nil)
		lcBody := lc.Body()
		if meta.CreateBeforeDestroy {
			lcBody.SetAttributeValue("create_before_destroy", cty.True)
		}
		if meta.PreventDestroy {
			lcBody.SetAttributeValue("prevent_destroy", cty.True)
		}
	}

	root.AppendNewline()
}

// ── Recursive block tree ─────────────────────────────────────────────────────

type blockNode struct {
	attrs    map[string]interface{}
	children map[string]*blockNode
}

func newBlockNode() *blockNode {
	return &blockNode{
		attrs:    make(map[string]interface{}),
		children: make(map[string]*blockNode),
	}
}

// buildBlockTree converts dotted-path NestedBlocks into a recursive tree.
func buildBlockTree(nested map[string]interface{}, todos map[string]string) map[string]*blockNode {
	roots := make(map[string]*blockNode)

	for dotPath, val := range nested {
		parts := strings.Split(dotPath, ".")
		if len(parts) == 0 {
			continue
		}

		rootName := parts[0]
		if _, ok := roots[rootName]; !ok {
			roots[rootName] = newBlockNode()
		}

		current := roots[rootName]
		for i := 1; i < len(parts)-1; i++ {
			childName := parts[i]
			if _, ok := current.children[childName]; !ok {
				current.children[childName] = newBlockNode()
			}
			current = current.children[childName]
		}

		if len(parts) == 1 {
			current.attrs["value"] = val
		} else {
			leafName := parts[len(parts)-1]
			current.attrs[leafName] = val
		}
	}

	return roots
}

// writeBlockTree recursively emits nested HCL blocks.
func writeBlockTree(body *hclwrite.Body, tree map[string]*blockNode, todos map[string]string, pathPrefix string) {
	for _, blockName := range sortedKeys(tree) {
		node := tree[blockName]

		body.AppendNewline()
		nb := body.AppendNewBlock(blockName, nil)
		nbBody := nb.Body()

		currentPath := blockName
		if pathPrefix != "" {
			currentPath = pathPrefix + "." + blockName
		}

		for _, attrName := range sortedKeys(node.attrs) {
			fullPath := currentPath + "." + attrName
			if todo, ok := todos[fullPath]; ok {
				nbBody.AppendUnstructuredTokens(hclwrite.Tokens{
					{Bytes: []byte(fmt.Sprintf("    # TODO: %s\n", todo))},
				})
			}
			writeAttr(nbBody, attrName, node.attrs[attrName])
		}

		if len(node.children) > 0 {
			writeBlockTree(nbBody, node.children, todos, currentPath)
		}
	}
}

func writeAttr(body *hclwrite.Body, key string, val interface{}) {
	key = strings.ReplaceAll(key, ".", "_")

	switch v := val.(type) {
	case string:
		if strings.HasPrefix(v, "${") && strings.HasSuffix(v, "}") {
			inner := v[2 : len(v)-1]
			body.SetAttributeRaw(key, hclwrite.Tokens{
				{Bytes: []byte(inner + "\n")},
			})
		} else {
			body.SetAttributeValue(key, cty.StringVal(v))
		}
	case bool:
		body.SetAttributeValue(key, cty.BoolVal(v))
	case float64:
		if v == float64(int64(v)) {
			body.SetAttributeValue(key, cty.NumberIntVal(int64(v)))
		} else {
			body.SetAttributeValue(key, cty.NumberFloatVal(v))
		}
	case int:
		body.SetAttributeValue(key, cty.NumberIntVal(int64(v)))
	case int64:
		body.SetAttributeValue(key, cty.NumberIntVal(v))
	case []interface{}:
		body.SetAttributeRaw(key, hclwrite.Tokens{
			{Bytes: []byte(sliceToHCL(v) + "\n")},
		})
	case map[string]interface{}:
		body.SetAttributeRaw(key, hclwrite.Tokens{
			{Bytes: []byte(mapToHCL(v) + "\n")},
		})
	case nil:
		// skip
	default:
		body.SetAttributeValue(key, cty.StringVal(fmt.Sprintf("%v", val)))
	}
}

func sliceToHCL(items []interface{}) string {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		parts = append(parts, valToHCLLiteral(item))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func mapToHCL(m map[string]interface{}) string {
	parts := make([]string, 0, len(m))
	for _, k := range sortedKeys(m) {
		parts = append(parts, fmt.Sprintf("    %s = %s", k, valToHCLLiteral(m[k])))
	}
	return "{\n" + strings.Join(parts, "\n") + "\n  }"
}

func valToHCLLiteral(v interface{}) string {
	switch t := v.(type) {
	case string:
		if strings.HasPrefix(t, "${") && strings.HasSuffix(t, "}") {
			return t[2 : len(t)-1]
		}
		return fmt.Sprintf("%q", t)
	case bool:
		if t {
			return "true"
		}
		return "false"
	case float64:
		if t == float64(int64(t)) {
			return fmt.Sprintf("%d", int64(t))
		}
		return fmt.Sprintf("%g", t)
	case nil:
		return "null"
	default:
		return fmt.Sprintf("%q", fmt.Sprintf("%v", v))
	}
}

func providerSource(provider string) string {
	switch provider {
	case "google":
		return "hashicorp/google"
	case "azurerm":
		return "hashicorp/azurerm"
	case "aws":
		return "hashicorp/aws"
	default:
		return "hashicorp/" + provider
	}
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func (g *Generator) writeWarnings(root *hclwrite.Body, warnings []ir.TranslationWarning) {
	root.AppendUnstructuredTokens(hclwrite.Tokens{
		{Bytes: []byte("\n# ── Translation Warnings ──────────────────────────────────────────\n")},
	})
	for _, w := range warnings {
		severity := "INFO"
		switch w.Severity {
		case ir.WarnManual:
			severity = "MANUAL"
		case ir.WarnSemantic:
			severity = "SEMANTIC"
		case ir.WarnMissing:
			severity = "MISSING"
		}
		root.AppendUnstructuredTokens(hclwrite.Tokens{
			{Bytes: []byte(fmt.Sprintf("# [%s] %s.%s: %s\n", severity, w.Resource, w.Attribute, w.Message))},
		})
	}
}
