# Generated by terra-translate — target provider: google
# Review ALL resources before applying. Attributes marked TODO require manual replacement.

terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}


# Translated from: aws_vpc.main
# Unmapped attrs (manual review): cidr_block, enable_dns_support, enable_dns_hostnames
 resource "google_compute_network" "main" {
    # TODO: auto-injected default; must replace with real value
 auto_create_subnetworks = false
  description                                                                            ={
    Environment = "production"
    Name = "main-vpc"
  }

    # TODO: auto-injected default; must replace with real value
 name                    = "TODO-network-name"
}


# Translated from: aws_subnet.app
 resource "google_compute_subnetwork" "app" {
  description                                                         ={
    Name = "app-subnet"
  }

  ip_cidr_range                                                       = "10.0.1.0/24"
    # TODO: auto-injected default; must replace with real value
 name = "TODO-subnet-name"
  network                                                             =google_compute_network.main.self_link

  region                                                              = "US-EAST1"
}


# Translated from: aws_security_group.web
# Translated from aws_security_group.web (no inline rules)
 resource "google_compute_firewall" "web" {
  description = "Allow HTTP and HTTPS inbound"
  name        = "web-sg"
  network     =google_compute_network.main.self_link

}


# Translated from: aws_instance.web
# Unmapped attrs (manual review): iam_instance_profile, key_name
 resource "google_compute_instance" "web" {
  labels                                                              ={
    Environment = "production"
    Name = "web-server"
    Role = "web"
  }

  machine_type                                                        = "e2-medium"
  metadata_startup_script                                             = "#!/bin/bash\napt-get update\napt-get install -y nginx\nsystemctl start nginx\n"
    # TODO: auto-injected default; must replace with real value
 name = "TODO-name"
  zone                                                                = "us-east-1a"

  boot_disk {

    initialize_params {
      image = "TODO:resolve-ami:ami-0c55b159cbfafe1f0"
    }
  }

  network_interface {
        # TODO: auto-injected default; must replace with real value
 network = "default"
    subnetwork                                                               =google_compute_subnetwork.app.self_link

  }

  lifecycle {
    create_before_destroy = true
  }
}


# Translated from: aws_s3_bucket.assets
 resource "google_storage_bucket" "assets" {
  force_destroy                                                           = false
  labels                                                                  ={
    Environment = "production"
    Name = "assets"
  }

    # TODO: auto-injected default; must replace with real value
 location = "US"
  name                                                                    = "my-app-assets-bucket"
}


# Translated from: aws_db_instance.app_db
# Primary SQL instance from aws_db_instance.app_db
 resource "google_sql_database_instance" "app_db" {
  database_version = "POSTGRES_14"
  name             = "app-database"

  settings {
    availability_type = "REGIONAL"
    disk_size         = 100
    tier              = "db-g1-small"
    user_labels       ={
    Environment = "production"
    Name = "app-db"
  }


    backup_configuration {
      enabled = true
    }
  }
}


# Translated from: aws_db_instance.app_db_db
# Database resource split from aws_db_instance.app_db
 resource "google_sql_database" "app_db_db" {
  instance =google_sql_database_instance.app_db.name

  name     = "default"
}


# Translated from: aws_db_instance.app_db_user
# Database user split from aws_db_instance.app_db
 resource "google_sql_user" "app_db_user" {
  instance                                                                     =google_sql_database_instance.app_db.name

  name                                                                         = "appuser"
    # TODO: SENSITIVE: consider google_secret_manager_secret_version
 password = "changeme"
}


# Translated from: aws_lambda_function.processor
# Unmapped attrs (manual review): environment
 resource "google_cloudfunctions2_function" "processor" {
  labels                                                                  ={
    Name = "event-processor"
  }

    # TODO: auto-injected default; must replace with real value
 location = "us-central1"
  name                                                                    = "event-processor"

  build_config {
    entry_point = "handler.main"
    runtime     = "python311"
  }

  service_config {
    available_memory = "512Mi"
    timeout_seconds  = 30
  }
}


# ── Translation Warnings ──────────────────────────────────────────
# [MANUAL] google_compute_network.main.name: required attribute injected with default — must be customised
# [MANUAL] google_compute_network.main.auto_create_subnetworks: required attribute injected with default — must be customised
# [MANUAL] google_compute_subnetwork.app.name: required attribute injected with default — must be customised
# [MANUAL] google_compute_instance.web.network_interface.network: required attribute injected with default — must be customised
# [MANUAL] google_compute_instance.web.name: required attribute injected with default — must be customised
# [MANUAL] google_storage_bucket.assets.location: required attribute injected with default — must be customised
# [MANUAL] google_cloudfunctions2_function.processor.location: required attribute injected with default — must be customised
